### PR TITLE
⬆️ HPC-8322: Update @material-ui/core

### PR DESCRIPTION
**Pull request by s0**
The version we were using was incompatible with the latest version of React.

### CODE REVIEW

**Review by unocha-hpc — APPROVED** [review]
Checks have passed and this pull request is ready for manual review

**Comment by Pl217** [comment]
Should we make an effort or create a ticket to [migrate from v4 to v5](https://mui.com/guides/migration-v4/)?

**Comment by s0** [comment]
> Should we make an effort or create a ticket to [migrate from v4 to v5](https://mui.com/guides/migration-v4/)?

Yeah that looks like a non-trivial change, we should do it but no need to block this regression fix. Ticket opened here: https://humanitarian.atlassian.net/browse/HPC-8326

**Comment by Pl217** [comment]
> Yeah that looks like a non-trivial change, we should do it but no need to block this regression fix. Ticket opened here: https://humanitarian.atlassian.net/browse/HPC-8326

Didn't mean for it to be blocking definitely. Thanks for creating the ticket

**Review by czmj — APPROVED** [review]

**Review by unocha-hpc — APPROVED** [review]
Checks have passed and this pull request is ready for manual review

**Pull request merged**
