### PR TITLE
HPC-9578 Add Apollo Client

### PR DESCRIPTION
**Pull request by Onitoxan**
## Nature of PR

- [ ]  Bug-fix
- [ ]  Hot-fix
- [X]  Feature
- [ ]  Testing
- [ ]  Rewrite
- [ ]  CI
- [ ]  Package update

## Description

Add Apollo client to make calls to GrapQL endpoints. Beside setting up Apollo client I added an `AbortSignal` for calls that are using our REST endpoints, like this when changing of page the petition gets cancelled.

Out of the box Apollo will let us have a cache system, that's why I remove the abort signals from petitions using it, once they are made they will not repeat themselves and they will be accessed form the cache.

Apollo allow use to use their own hooks like `useQuery`, but since we have already implemented in the project our own `dataLoader` I was not sure what would be the best idea. Also, reusing our `dataLoader` makes the implementation easier with less changes.

## How to test changes

To test changes I feel the key places to look are:
1. `model.ts` I added Apollo client here and we should double check that this should be the place where it belongs, if it's not the case we need to see where would that be.
2. Navigate through Flow and Pending Flow pages and play around with searches to verify that the cache policy is no making as return false data.

## TODO:

Maybe we could investigate what else could we do with Apollo Client, there is a TODO comment in the code that we could look into:

> TODO: Dynamically fetch only necessary fields, Ex: if we don't display 'NewMoney' we shouldn't ask for it

And I suppose Apollo offers some kind of solution for this. In any case, if we feel is the case we could open a ticket in the future.

### CODE REVIEW

**Review by unocha-hpc — APPROVED** [review]
Checks have passed and this pull request is ready for manual review

**Review by unocha-hpc — APPROVED** [review]
Checks have passed and this pull request is ready for manual review

**Review by unocha-hpc — APPROVED** [review]
Checks have passed and this pull request is ready for manual review

**Review by unocha-hpc — APPROVED** [review]
Checks have passed and this pull request is ready for manual review

**Review by unocha-hpc — APPROVED** [review]
Checks have passed and this pull request is ready for manual review

**Review by unocha-hpc — APPROVED** [review]
Checks have passed and this pull request is ready for manual review

**Review by unocha-hpc — APPROVED** [review]
Checks have passed and this pull request is ready for manual review

**Review by unocha-hpc — APPROVED** [review]
Checks have passed and this pull request is ready for manual review

**Review by manelcecs — COMMENTED** [review]
Everything looks good!

We'll need to rebase this branch with all the new work and previously merged work too.

The only thing pending is to do a pair session with you to review the functionality and next steps to do (such as what can do Apollo Server to help to reduce the payload or to maintain the same data structure/schema)

**Review by unocha-hpc — APPROVED** [review]
Checks have passed and this pull request is ready for manual review

**Pull request merged**
