### PR TITLE
📦️ Test Spanish translation and deploy to demo

### PR DESCRIPTION
**Pull request by Pl217**
This PR is used to build Docker image for Spanish translation - #351 and deploy to demo (manually in Jenkins) for testing. Upon completion, the PR will be closed.

### CODE REVIEW

**Review by unocha-hpc — APPROVED** [review]
Docker image has been successfully built and pushed as: `public.ecr.aws/unocha/hpc-cdm:v1.3.10-test-pre`

Please deploy this image to a development environment, and test it is working as expected before merging this pull request.

**Review by unocha-hpc — APPROVED** [review]
Docker image has been successfully built and pushed as: `public.ecr.aws/unocha/hpc-cdm:v1.3.10-test-pre`

Please deploy this image to a development environment, and test it is working as expected before merging this pull request.

**Review by unocha-hpc — APPROVED** [review]
Docker image has been successfully built and pushed as: `public.ecr.aws/unocha/hpc-cdm:v1.3.10-test-pre`

Please deploy this image to a development environment, and test it is working as expected before merging this pull request.

**Comment by Pl217** [comment]
Spanish translation is successfully tested on demo. Closing this ticket now.

**Pull request closed without merging**
